CREATE TABLE users (
 	email VARCHAR(255),
    password VARCHAR(255),
    jwt VARCHAR(255),
    id serial PRIMARY KEY,
    name VARCHAR(50),
    latitude INT,
    longitude INT,
    location VARCHAR(255),
    likes INT[],
    age INT,
    birthday INT,
    monthofbirth INT,
    yearofbirth INT,
    gender INT,
    gendervapor INT,
    photomain INT,
    photolink TEXT[],
    signzodiac INT,
    education INT,
    fieldofactivity INT,
    maritalstatus INT,
    children INT,
    religion INT,
    rise INT,
    smoke INT,
    alcohol INT,
    discription VARCHAR(255),
    profit INT,
    interests TEXT[],
    ilikecharacter INT[],
    idontlikecharacter INT[],
    vapors INT[],
    likepeoples INT[],
    dislikepeoples INT[]
);
