export const fakeData = [
    {
        email: '1@gmail.com',
        password: '$2a$13$Wzt2dof.s0RbuojuKcsKc.TqKvpcShQo4tKGm.7VaC6LbBJDsS6ey', // 123456789
        jwt: '',
        id: 1,
        name: 'Eva',
        latitude: 0,
        longitude: 0,
        location: 'Ryazan',
        likes: 12,
        age: 22,
        birthday: 5,
        monthOfBirth: 5,
        yearOfBirth: 2000,
        gender: 1,
        genderVapor: 0,
        photoMain: 1,
        photoLink: [
            'https://i0.wp.com/globalzonetoday.com/wp-content/uploads/2020/12/Kiara-Cole.jpg', 
            'https://www.eaglesvine.com/wp-content/uploads/2021/10/Kiara-Cole_02-780x470.jpg'
        ],
        signZodiac: 5,
        education: 2,
        fieldOfActivity: 1,
        maritalStatus: 0,
        children: 2,
        religion: 0,
        rise: 2,
        smoke: 1,
        alcohol: 1,
        discription: 'Приветики, меня зовут Ева',
        profit: 2,
        iLikeСharacter: [0, 5, 7],
        iDontLikeСharacter: [3, 8, 10],
    },
    {
        email: '2@gmail.com',
        password: '$2a$13$6Tp9UvShlOnLxMFpi7klJO4Qi/zqvEGBUB0xc8nJHATHNeufXs176', // 223456789
        jwt: '',
        id: 2,
        name: 'Diana',
        latitude: 0,
        longitude: 0,
        location: 'Ryazan',
        likes: 15,
        age: 24,
        birthday: 9,
        monthOfBirth: 4,
        yearOfBirth: 1998,
        gender: 1,
        genderVapor: 0,
        photoMain: 1,
        photoLink: [
            'https://pikabu.ru/story/lyubimyie_aktrisyi_dlya_druga_39_kacey_jordan_4067259', 
            'https://files.theblemish.com/images/2011/01/kacey-jordan-bikini-750x399.jpg',
            'https://images.scrolller.com/zepto/kacey-jordan-dqgnlsfbzg-602x900.jpg',
        ],
        signZodiac: 3,
        education: 3,
        fieldOfActivity: 1,
        maritalStatus: 2,
        children: 1,
        religion: 3,
        rise: 1,
        smoke: 0,
        alcohol: 0,
        discription: 'Приветики, меня зовут Диана',
        profit: 2,
        iLikeСharacter: [0, 5, 7],
        iDontLikeСharacter: [3, 8, 10],
    },
];
